//
//  ProductGenerator.swift
//  BuildMe
//
//  Created by Nazrin Sultanlı on 10.11.23.
//

import Foundation
import RealmSwift
class ProductGenerator{
    let myRealm = try! Realm()
    var productData = [Product(categoryType: .laminate,
                               brandName: .swiss,
                               modelName: .swiss1,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image1",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: false,
                               new: true),
                       Product(categoryType: .laminate,
                               brandName: .swiss,
                               modelName: .swiss2,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image2",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: true,
                               new: true),
                       Product(categoryType: .laminate,
                               brandName: .krono,
                               modelName: .krono1,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image3",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: false,
                               new: true),
                       Product(categoryType: .laminate,
                               brandName: .krono,
                               modelName: .krono2,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image4",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: false,
                               new: true),
                       Product(categoryType: .asmaTavan,
                               brandName: .tavan,
                               modelName: .tavan1,
                               modelCode: "212212",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 3,
                               imageName: "image5",
                               definition: "asa sas sas as sa sa s",
                               featured: false,
                               discounted: true,
                               new: false),
                       Product(categoryType: .asmaTavan,
                               brandName: .tavan,
                               modelName: .tavan2,
                               modelCode: "90909",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image6",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: true,
                               new: true),
                       Product(categoryType: .kafel,
                               brandName: .kafell,
                               modelName: .kafell1,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image7",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: false,
                               new: true),
                       Product(categoryType: .kafel,
                               brandName: .kafell,
                               modelName: .krono2,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image8",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: false,
                               new: true),
                       Product(categoryType: .ceramics,
                               brandName: .ceramika,
                               modelName: .ceramika1,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image9",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: false,
                               new: true),
                       Product(categoryType: .ceramics,
                               brandName: .ceramika,
                               modelName: .ceramika2,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image10",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: false,
                               new: true),
                       Product(categoryType: .accesories,
                               brandName: .accesor,
                               modelName: .accesor1,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image1",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: false,
                               new: true),
                       Product(categoryType: .accesories,
                               brandName: .accesor,
                               modelName: .accesor2,
                               modelCode: "121221",
                               price: 20,
                               quantity: 10,
                               stock: true,
                               rating: 5,
                               imageName: "image1",
                               definition: "asa sas sas as sa sa s",
                               featured: true,
                               discounted: true,
                               new: true),
    ]
    
    
    func saveItems() {
        do{
            try myRealm.write{
                myRealm.add(productData)
                fetch()
            }
        } catch{
            print(error.localizedDescription)
        }
    }
    
    func fetch(){
        let data = myRealm.objects(Product.self)
        productData.removeAll()
        productData.append(contentsOf: data)
        
    }
    
    
}
